//此文件为src/task/generateCode.ts自动生成(npm脚本: json_model), 请勿修改
export const imgs = {
      agenda: require('./img/agenda.png').default,
      banner_ns: require('./img/banner-ns.png').default,
      banner_sct: require('./img/banner-sct.png').default,
      banner: require('./img/banner.png').default,
      bg: require('./img/bg.jpg').default,
      chengji: require('./img/chengji.png').default,
      fabu: require('./img/fabu.png').default,
      faxian: require('./img/faxian.png').default,
      female: require('./img/female.png').default,
      fengcai: require('./img/fengcai.png').default,
      ic_launcher: require('./img/ic_launcher.png').default,
      ic_launcher_bg: require('./img/ic_launcher_bg.png').default,
      kaoqin: require('./img/kaoqin.png').default,
      kebiao: require('./img/kebiao.png').default,
      male: require('./img/male.png').default,
      min: require('./img/min.png').default,
      mine: require('./img/mine.png').default,
      n_shouye: require('./img/n-shouye.png').default,
      pingia: require('./img/pingia.png').default,
      qingjia: require('./img/qingjia.png').default,
      saoma: require('./img/saoma.png').default,
      set_faxian: require('./img/set-faxian.png').default,
      set_mine: require('./img/set-mine.png').default,
      set_xiaoxi: require('./img/set-xiaoxi.png').default,
      shouye: require('./img/shouye.png').default,
      tianqi: require('./img/tianqi.png').default,
      tixing: require('./img/tixing.png').default,
      xiaoxi: require('./img/xiaoxi.png').default,
      ziyuan: require('./img/ziyuan.png').default,
      zuoye: require('./img/zuoye.png').default,
}
