//此文件为src/task/generateCode.ts自动生成(npm脚本: json_model), 请勿修改
export const imgs = {
      agenda: require('./img/agenda.png'),
      banner_ns: require('./img/banner-ns.png'),
      banner_sct: require('./img/banner-sct.png'),
      banner: require('./img/banner.png'),
      bg: require('./img/bg.jpg'),
      chengji: require('./img/chengji.png'),
      fabu: require('./img/fabu.png'),
      faxian: require('./img/faxian.png'),
      female: require('./img/female.png'),
      fengcai: require('./img/fengcai.png'),
      ic_launcher: require('./img/ic_launcher.png'),
      ic_launcher_bg: require('./img/ic_launcher_bg.png'),
      kaoqin: require('./img/kaoqin.png'),
      kebiao: require('./img/kebiao.png'),
      male: require('./img/male.png'),
      min: require('./img/min.png'),
      mine: require('./img/mine.png'),
      n_shouye: require('./img/n-shouye.png'),
      pingia: require('./img/pingia.png'),
      qingjia: require('./img/qingjia.png'),
      saoma: require('./img/saoma.png'),
      set_faxian: require('./img/set-faxian.png'),
      set_mine: require('./img/set-mine.png'),
      set_xiaoxi: require('./img/set-xiaoxi.png'),
      shouye: require('./img/shouye.png'),
      tianqi: require('./img/tianqi.png'),
      tixing: require('./img/tixing.png'),
      xiaoxi: require('./img/xiaoxi.png'),
      ziyuan: require('./img/ziyuan.png'),
      zuoye: require('./img/zuoye.png'),
}
